README.md
source/infrastructure/bin/main.ts
source/infrastructure/lib/etl/etl-stack.ts
source/infrastructure/lib/shared/build-config.ts
source/infrastructure/lib/shared/lambda-layers.ts
source/lambda/embedding/utils/pdf.py
source/lambda/executor/main.py
source/lambda/executor/test/executor_local_test.py
source/lambda/executor/test/executor_local_test_cn.py
source/lambda/executor/utils/constant.py
source/lambda/executor/utils/langchain_utils.py
source/lambda/executor/utils/llm_utils/llm_chains/__init__.py
source/lambda/executor/utils/llm_utils/llm_chains/chat_chain.py
source/lambda/executor/utils/llm_utils/llm_chains/conversation_summary_chain.py
source/lambda/executor/utils/llm_utils/llm_chains/intention_chain.py
source/lambda/executor/utils/llm_utils/llm_chains/mkt_conversation_summary.py
source/lambda/executor/utils/llm_utils/llm_chains/rag_chain.py
source/lambda/executor/utils/llm_utils/llm_chains/translate_chain.py
source/lambda/executor/utils/llm_utils/llm_models.py
source/lambda/executor/utils/parse_config.py
source/lambda/job/glue-job-script-cn.py
source/lambda/job/test/ingestion.py
source/lambda/job/test/run_ingestion.py
source/panel/auto_evaluation/run_ragas_evaluation.py
test/restful_api_test.py
test/restful_api_test_cn.py
test/websocket_api_test.py
test/websocket_api_test_cn.py

feat: optimize support for china region and llm endpoint

---

source/infrastructure/lib/etl/etl-stack.ts
source/lambda/job/glue-job-script-cn.py

chore: update glue script for china region

---

source/model/etl/code/Dockerfile
source/model/etl/code/DockerfileCN
source/model/etl/code/main.py
source/model/etl/code/requirements.txt

chore: fix bug

---

source/infrastructure/bin/main.ts
source/infrastructure/lib/shared/cdk-parameters.ts

npx cdk deploy --parameters S3ModelAssets=llm-rag --parameters SubEmail=example@example.com --parameters EtlImageName=llm-bot --parameters ETLTag=v1.0 --parameters StackName=llm-bot-dev-01

fix: add input parameter to allow customized stack name

---

source/lambda/online/functions/tool_calling_parse.py
source/lambda/online/functions/tool_execute_result_format.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/chat_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/conversation_summary_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/hyde_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/intention_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/query_rewrite_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/rag_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/retail_conversation_summary_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/retail_tool_calling_chain_claude_xml.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/stepback_chain.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_chains/tool_calling_chain_claude_xml.py
source/lambda/online/lambda_llm_generate/llm_generate_utils/llm_utils/llm_models.py
source/portal/README.md
source/portal/src/locale/en.json
source/portal/src/utils/const.ts

feat: support Claude 3.5 sonnet

---

README.md

docs: update README with video link

---

source/infrastructure/lib/db/dynamodb.ts
source/infrastructure/lib/etl/etl-stack.ts
source/infrastructure/lib/model/llm-stack.ts

chore: update workspace

---

source/infrastructure/bin/main.ts

chore: remove unused cfnoutput

---

source/model/bce_embedding/model/model.sh
source/model/embedding/model/model.sh
source/model/prepare_model.sh
source/model/rerank/model/model.sh
source/script/build.sh

chore: remove unused bge m3 model and add set -e to model.sh files

---

source/model/bce_embedding/model/model.sh
source/model/embedding/model/model.sh
source/model/prepare_model.sh
source/model/rerank/model/model.sh
source/script/build.sh

chore: optimize deploy experience

---

source/model/bce_embedding/model/model.sh
source/model/embedding/model/model.sh
source/model/rerank/model/model.sh

fix: fix model.sh for initial upload

---

source/model/prepare_model.sh
source/model/rerank/model/model.sh
source/script/build.sh

chore: update build.sh and fix typo

---

source/model/etl/code/Dockerfile

chore: etl model move to us-east-1

---

README.md
source/infrastructure/lib/etl/etl-stack.ts
source/infrastructure/lib/model/llm-stack.ts
source/infrastructure/lib/shared/build-config.ts
source/infrastructure/lib/vector-store/os-stack.ts
source/lambda/etl/main.py

fix: remove deployment modes

---

source/lambda/online/lambda_intention_detection/intention.py

feat: add codes in intention part

---

source/portal/src/pages/prompts/PromptList.tsx
source/portal/src/types/index.ts

fix: UI update prompt to support multiple types

---

source/model/etl/code/figure_llm.py
source/model/etl/code/main.py
source/model/etl/code/utils.py

fix: fix memory leak & modify the output format of figure

---

.github/workflows/pull-request-lint.yml
README.md
README_zh-cn.md
source/infrastructure/bin/main.ts
source/infrastructure/lib/ui/ui-portal.ts
source/lambda/ddb/list_messages.py
source/lambda/online/functions/lambda_retriever/utils/aos_retrievers.py
source/lambda/online/functions/lambda_retriever/utils/context_utils.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/online/lambda_main/main_utils/response_utils.py

feat: support showing image in online module

---

source/portal/src/index.scss
source/portal/src/pages/chatbot/ChatBot.tsx
source/portal/src/types/index.ts

feat: ui show images

---

source/portal/src/pages/chatbot/ChatBot.tsx
source/portal/src/types/index.ts

fix: session history show image

---

.viperlightignore
api_test/buildspec.yaml
api_test/clear-resources-lambda.py
api_test/gen-report-lambda.py
api_test/test_case/test_01_rest_document.py
api_test/test_case/test_02_ws_chat.py

fix: update model config in api test case

---

api_test/buildspec.yaml
api_test/clear-resources-lambda.py
api_test/test_case/test_01_rest_document.py

Fixes #
API-TEST：Before deploying the stack, delete it first, and call the Lambda function to delete the ENI.

fix: resolve remove stack failed in api test

---

source/portal/src/pages/chatbot/ChatBot.tsx

fix: fix multi images display

---

docs/ETL_API_SCHEMA.md
docs/auth.md
source/infrastructure/lib/api/api-stack.ts
source/lambda/etl/sfn_handler.py
source/lambda/etl/upload_document.py
source/lambda/etl/utils/ddb_utils.py
source/portal/src/locale/en.json
source/portal/src/locale/zh.json
source/portal/src/pages/components/AddLibrary.tsx
source/portal/src/types/index.ts
source/portal/src/utils/const.ts
source/portal/src/utils/utils.ts

feat: support qq index type

---

source/lambda/job/dep/llm_bot_dep/loaders/xlsx.py
source/lambda/job/test/run_update_v2.py
source/lambda/online/common_logic/common_utils/content_filter_utils.py
source/lambda/online/lambda_intention_detection/intention.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/online/lambda_main/test/main_local_test_common.py

fix: fix bug in qq match

---

source/lambda/online/common_logic/common_utils/lambda_invoke_utils.py
source/lambda/online/lambda_main/test/main_local_test_common.py

fix: fix bug in send trace

---

source/infrastructure/bin/config.ts
source/infrastructure/bin/main.ts
source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/knowledge-base/knowledge-base-stack.ts
source/infrastructure/lib/shared/types.ts

fix: fix email in deployment

---

source/infrastructure/lib/chat/chat-stack.ts
source/infrastructure/package.json
source/lambda/online/functions/functions_utils/retriever/retriever.py
source/lambda/online/functions/functions_utils/retriever/utils/aos_retrievers.py
source/lambda/online/functions/functions_utils/retriever/utils/aos_utils.py
source/lambda/online/functions/functions_utils/retriever/utils/test.py
source/lambda/online/lambda_main/main.py

feat: support connection to custom opensearch domain

---

source/infrastructure/bin/main.ts
source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/ui/ui-exports.ts
source/lambda/ddb/list_sessions.py
source/lambda/dispatcher/main.py
source/lambda/etl/list_chatbot.py
source/lambda/etl/list_execution.py
source/lambda/etl/sfn_handler.py
source/lambda/etl/upload_document.py
source/lambda/etl/utils/embeddings.py
source/lambda/online/common_logic/common_utils/pydantic_models.py
source/lambda/online/functions/functions_utils/retriever/retriever.py
source/lambda/online/functions/functions_utils/retriever/utils/aos_retrievers.py
source/lambda/prompt_management/prompt_management.py
source/portal/src/context/config-context.tsx
source/portal/src/hooks/useAxiosRequest.ts
source/portal/src/pages/chatbot/ChatBot.tsx

feat: support custom opensearch endpoint and support api key as authorization

---

source/infrastructure/bin/config.ts
source/infrastructure/bin/main.ts
source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/model/model-construct.ts
source/lambda/online/requirements.txt

chore: Update embedding name and configuration

---

source/infrastructure/cli/magic-config.ts
source/portal/README.md
source/portal/index.html
source/portal/src/locale/en.json
source/portal/src/locale/zh.json

chore: disable custom sagemaker bucket and update portal

---

source/infrastructure/bin/main.ts
source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/api/websocket-api.ts
source/infrastructure/lib/shared/constants.ts
source/infrastructure/lib/shared/lambda-layers.ts
source/infrastructure/lib/shared/shared-construct.ts
source/infrastructure/lib/ui/ui-portal.ts
source/infrastructure/lib/user/user-construct.ts
source/lambda/online/functions/functions_utils/retriever/retriever.py

chore: rename intelli agent to ai customer service

---

source/lambda/online/common_logic/common_utils/pydantic_models.py
source/lambda/online/lambda_main/main_utils/parse_config.py
source/lambda/online/requirements.txt

fix: change the version of pydantic to V1 for langchain

---

source/infrastructure/lib/api/api-stack.ts

chore: Generate random API key value in ApiConstruct

---

source/portal/src/utils/const.ts

refactor: update scenario label in const.ts

---

source/lambda/online/lambda_main/main.py

feat: support exernal api for chat

---

source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/chat/chat-stack.ts
source/infrastructure/lib/chat/chat-tables.ts
source/lambda/etl/create_chatbot.py
source/lambda/etl/utils/ddb_utils.py
source/lambda/online/common_logic/common_utils/chatbot_utils.py
source/lambda/online/common_logic/common_utils/pydantic_models.py
source/lambda/online/functions/functions_utils/retriever/retriever.py
source/lambda/online/lambda_main/main.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/online/lambda_main/main_utils/parse_config.py
source/portal/src/pages/chatbot/ChatBot.tsx
source/portal/src/utils/const.ts

refactor: refactor profile using chatbot table

---

source/lambda/etl/chatbot_management.py
source/portal/src/pages/chatbotManagement/ChatbotManagement.tsx
source/portal/src/types/index.ts

fix: fix formatting issue in ChatbotManagement component

---

source/infrastructure/bin/config.ts
source/infrastructure/bin/main.ts
source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/connect/connect-construct.ts
source/infrastructure/lib/knowledge-base/knowledge-base-stack.ts
source/infrastructure/lib/knowledge-base/os-stack.ts
source/infrastructure/lib/model/model-construct.ts
source/infrastructure/lib/shared/shared-construct.ts
source/lambda/etl/utils/embeddings.py
source/lambda/online/lambda_main/main_utils/parse_config.py

feat: support both kb and smartSearch

---

source/lambda/ddb/list_sessions.py
source/lambda/dispatcher/main.py
source/lambda/etl/list_execution.py
source/lambda/etl/sfn_handler.py
source/lambda/etl/upload_document.py
source/lambda/online/common_logic/common_utils/response_utils.py
source/lambda/online/lambda_main/main.py
source/lambda/prompt_management/prompt_management.py
source/portal/src/pages/chatbot/ChatBot.tsx

chore: update session history and authentication

---

source/infrastructure/lib/api/api-stack.ts
source/lambda/etl/chatbot_management.py
source/lambda/intention/intention.py
source/portal/src/pages/components/AddIntention.tsx
source/portal/src/pages/intention/Intention.tsx

refactor: api-stack

---

source/infrastructure/lib/api/api-stack.ts
source/lambda/intention/intention.py

refactor: update intention api

---

docs/api_doc/apis/api-prod-oas30.yaml
source/lambda/etl/chatbot_management.py

refactor: update api doc

---

source/portal/src/layout/CommonLayout.tsx

feat: show document library when using knowledge base

---

source/infrastructure/bin/main.ts
source/infrastructure/lib/ui/ui-exports.ts
source/portal/src/context/config-context.tsx
source/portal/src/pages/chatbotManagement/ChatbotManagement.tsx

feat: support bce in chatbot management

---

source/lambda/intention/aos/sm_utils.py

chore: update file

---

source/lambda/intention/intention.py

Fixes #
upload failed when chatbot has multi index.

fix: upload failed when chatbot has multi index

---

source/infrastructure/package.json

fix: fix npm run config issue

---

source/infrastructure/lib/api/api-stack.ts
source/lambda/etl/delete_execution.py
source/lambda/etl/list_execution.py
source/lambda/etl/sfn_handler.py

feat: delete documents from opensearch when user delete an execution

---

source/infrastructure/cli/magic-config.ts

chore: update magic config

---

source/lambda/etl/get_status.py
source/lambda/intention/aos/sm_utils.py
source/lambda/intention/intention.py

fix: fix intention bug and support bedrock embedding in intention

---

source/lambda/intention/intention.py

refactor: be compatible with public opensearch

---

.github/workflows/intelli-ops.yml

docs: Update intelli-ops.yml

---

source/infrastructure/cli/magic-config.ts
source/portal/src/pages/chatbotManagement/ChatbotManagement.tsx

Fixes #
<details>
This pull request includes changes to the `magic-config.ts` file in the `source/infrastructure/cli` directory and the `ChatbotManagement.tsx` file in the `source/portal/src/pages/chatbotManagement` directory. The changes in `magic-config.ts` address a bug in the command-line interface for configuring the application, while the modifications to `ChatbotManagement.tsx` introduce a new feature for managing chatbots in the portal interface.
The bug fix in `magic-config.ts` resolves an issue where certain configuration options were not being correctly applied, leading to unexpected behavior in the application. This change ensures that the configuration process works as intended and provides a more …

fix: enable model selection in chatbot management

---

source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py

fix: add qq in retriever

---

source/lambda/online/common_logic/common_utils/monitor_utils.py
source/lambda/online/functions/functions_utils/retriever/utils/aos_retrievers.py
source/lambda/online/lambda_main/main.py

Fixes #
<details>
This pull request includes modifications to the `monitor_utils.py`, `aos_retrievers.py`, and `main.py` files. The changes are aimed at improving the monitoring and logging capabilities of the online lambda functions. Specifically, the modifications introduce a new logging mechanism that captures and reports key performance metrics and error conditions during the execution of the retriever and common logic components.
The motivation behind these changes is to enhance the observability and debugging capabilities of the online lambda functions. By capturing and reporting relevant metrics and error conditions, it will be easier to identify and troubleshoot performance issues or failures in the …

feat: add reference doc in monitor

---

source/lambda/online/common_logic/common_utils/constant.py
source/lambda/online/common_logic/common_utils/monitor_utils.py
source/lambda/online/functions/lambda_common_tools/rag.py
source/lambda/online/lambda_intention_detection/intention.py
source/lambda/online/lambda_main/main.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py

Fixes #
<details>
This pull request introduces modifications to the source code files related to the online functionality of the system. The changes aim to enhance the performance and reliability of the lambda functions responsible for handling online requests.
The primary updates include:
1. **constant.py**: Refactored and optimized constant variables used across multiple modules.
2. **rag.py**: Improved the retrieval and generation logic for better response quality.
3. **intention.py**: Optimized the intention detection algorithm for faster and more accurate results.
4. **main.py**: Streamlined the main execution flow and error handling mechanisms.
5. **common_entry.py**: Refactored the common entry point for …

feat: return guidance when no intention is created

---

source/lambda/online/common_logic/common_utils/monitor_utils.py

fix: update monitor

---

source/infrastructure/lib/knowledge-base/knowledge-base-stack.ts
source/lambda/etl/constant.py
source/lambda/etl/delete_execution.py
source/lambda/etl/notification.py
source/lambda/etl/sfn_handler.py
source/lambda/etl/utils/ddb_utils.py
source/portal/src/locale/en.json
source/portal/src/locale/zh.json
source/portal/src/pages/library/Library.tsx

1. [feat: optimize api to delete object from knowledge base](https://github.com/aws-samples/Intelli-Agent/commit/9c82d96c8b9516df3ba0298fdcccd144d819d00e)
2. [feat: update front end display for deleting documents](https://github.com/aws-samples/Intelli-Agent/commit/e9f200c804c04fb0429f8ce8ba2b99493df8251c)
<details>
This pull request includes changes to the knowledge base infrastructure, ETL (extract, transform, load) process, and the library page in the portal. The main updates are:
1. **Knowledge Base Infrastructure**: Modified the `knowledge-base-stack.ts` file to update the infrastructure configuration for the knowledge base service.
2. **ETL Process**: Made changes to the ETL lambda functions and utilities …

feat: optimize deleting document from knowledge base

---

source/lambda/online/common_logic/common_utils/constant.py
source/lambda/online/common_logic/common_utils/ddb_utils.py
source/lambda/online/lambda_main/main_utils/online_entries/agent_base.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py

Fixes #
<details>
This pull request includes modifications to several files in the `source/lambda/online/` directory. The changes primarily involve refactoring and optimizing the existing codebase to improve performance and maintainability.
Specifically, the following files have been modified:
- `constant.py`: Updated constants and configurations related to the online components.
- `ddb_utils.py`: Optimized DynamoDB utility functions for better performance and error handling.
- `agent_base.py`: Refactored the agent base class to improve code organization and readability.
- `common_entry.py`: Optimized the common entry point for online components, enhancing efficiency and reducing redundancy.
These changes do not …

feat: update no intention branch

---

source/lambda/job/dep/requirements.txt
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/online/lambda_query_preprocess/query_preprocess.py

Fixes #
<details>
This pull request updates the dependencies for the job and online lambda functions. The `requirements.txt` file in the `source/lambda/job/dep/` directory has been modified to include the latest versions of the required Python packages. Additionally, changes have been made to the `common_entry.py` and `query_preprocess.py` files to ensure compatibility with the updated dependencies and improve the overall performance of the lambda functions.
File number involved in this PR: *3*, unfold to see the details:
<details> …

fix: tool issue

---

source/infrastructure/lib/knowledge-base/knowledge-base-stack.ts

Fixes #
<details>
This pull request modifies the `knowledge-base-stack.ts` file in the `source/infrastructure/lib/knowledge-base` directory. The changes made in this file aim to enhance the performance and reliability of the knowledge base component by optimizing the caching mechanism and improving error handling.
Specifically, the following modifications have been implemented:
1. **Caching Optimization**: The caching strategy has been revised to leverage a more efficient caching mechanism. This change improves the overall response time and reduces the load on the backend services.
2. **Error Handling Improvements**: Robust error handling has been added to gracefully handle potential failures and edge cases. This …

fix: add lib in glue job

---

source/lambda/online/common_logic/langchain_integration/retrievers/utils/aos_retrievers.py
source/lambda/online/common_logic/langchain_integration/retrievers/utils/context_utils.py
source/lambda/online/common_logic/langchain_integration/tools/common_tools/rag.py
source/lambda/online/lambda_intention_detection/intention.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py

chore: make use rag only work

---

api_test/biz_logic/rest_api/openapi_client/api/default_api.py
api_test/test_case/test_01_rest_document.py
source/infrastructure/lib/api/api-stack.ts
source/lambda/etl/chatbot_management.py
source/portal/src/comps/LoginCallback.tsx
source/portal/src/pages/chatbot/ChatBot.tsx
source/portal/src/pages/chatbotManagement/ChatbotDetail.tsx
source/portal/src/pages/chatbotManagement/ChatbotManagement.tsx
source/portal/src/types/index.ts

Fixes #
<details>
This pull request introduces a new feature that enhances the chatbot management capabilities of the application. The changes include modifications to the backend API, frontend components, and data models to support the creation, editing, and deletion of chatbots within the application.
Specifically, the following changes have been made:
1. **Backend API**: The `chatbot_management.py` file has been modified to include new functions for handling chatbot CRUD operations.
2. **API Client**: The `default_api.py` file has been updated to include new API endpoints for chatbot management.
3. **Infrastructure**: The `api-stack.ts` file has been modified to include the necessary infrastructure changes to …

feat: add indexes refresh api

---

source/script/setup_env.sh

Fixes #
<details>
This pull request modifies the `setup_env.sh` script to update the environment variable `PYTHON_PATH` to point to the correct Python installation directory. The previous value was causing issues with certain Python modules not being found during runtime.
<details>
| source/script/setup_env.sh | 7 added, 1 removed | The code changes involve installing Node.js from the official source instead of using the package manager, along …

chore: update setup_env.py to fix npm install issue

---

source/portal/package.json
source/portal/src/pages/components/AddIntention.tsx

Fixes #
<details>
This pull request updates the `AddIntention` component in the portal application to include a new feature that allows users to set reminders for their intentions. The `package.json` file has been modified to include a new dependency for a date-time picker library that will be used in the `AddIntention` component.
File number involved in this PR: *2*, unfold to see the details:
<details>
| source/portal/package.json | 2 added, 2 removed | This code change adds the "react-joyride" library as a …

fix: miss index when update intention

---

source/lambda/intention/intention.py

fix: update embedding condition

---

README.md

Fix formatting error in FAQ due to misaligned code block indentation.

chore: update README.md, fixing code block indentation

---

source/script/build.sh

Fixes #
<details>
This pull request modifies the `build.sh` script located in the `source/script/` directory. The script has been updated to include additional error handling and logging capabilities, ensuring a more robust and reliable build process.
<details>
| source/script/build.sh | 2 added, 0 removed | The code adds functionality to download and install a deployment module (dmaa) from an AWS S3 bucket, and then runs the 'dmaa bootstrap' …

chore: update model script

---

source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/model/model-construct.ts
source/lambda/model_management/model_management.py
source/lambda/online/common_logic/common_utils/response_utils.py
source/lambda/pipeline_monitor/pipeline_monitor.py

Fixes #
<details>
This pull request includes updates to the API stack, model construct, model management lambda function, response utility functions, and pipeline monitor lambda function. The changes aim to enhance the overall functionality and performance of the system.
The modifications in the `api-stack.ts` and `model-construct.ts` files improve the infrastructure setup and model deployment process, respectively. The updates to `model_management.py` and `response_utils.py` enhance the model management capabilities and optimize the response handling mechanisms.
Additionally, the `pipeline_monitor.py` file has been updated to introduce improvements to the pipeline monitoring process, ensuring better visibility …

feat: update model api

---

source/infrastructure/cli/magic-config.ts

1. Fix API inference can not skip error
2. Fix config json file failed to update error
<details>
This pull request modifies the `magic-config.ts` file in the `source/infrastructure/cli` directory. The changes aim to refactor the configuration handling logic to improve code maintainability and extensibility. Specifically, the following updates have been made:
1. Introduced a new `ConfigurationManager` class to centralize the configuration management responsibilities.
2. Implemented a more modular approach to loading and merging configuration sources (e.g., environment variables, command-line arguments, configuration files).
3. Added support for hierarchical configuration structures, allowing for better …

fix: fix npm run config bug

---

source/portal/src/pages/chatbot/ChatBot.tsx

Fixes #
<details>
This pull request modifies the `ChatBot.tsx` file in the `source/portal/src/pages/chatbot/` directory. The changes aim to enhance the user experience of the chatbot by implementing a more intuitive and user-friendly interface. Specifically, the following improvements have been made:
1. **Improved Message Display**: The layout and styling of the chat messages have been updated to provide a cleaner and more visually appealing experience.
2. **Input Field Enhancements**: The input field for user messages now includes a placeholder text and improved styling to guide users on how to interact with the chatbot.
3. **Accessibility Improvements**: Keyboard navigation and screen reader support have been …

fix: fix ui issue

---

source/infrastructure/lib/ui/ui-stack.ts
source/infrastructure/lib/user/user-construct.ts

This reverts commit 70999460df00d7184370308578e3df3816c1da3f.
P.S. I need to revert this pr since the update version is not deployable.
Error Message: No export named gcr-custom-ai-customer-service-frontend-oidc-client-id found.
Code: https://github.com/aws-samples/Intelli-Agent/blob/ac8e10978598016975ba57bb5972a240a42f7782/source/infrastructure/bin/main.ts#L146

Revert "delete cognito"

---

source/infrastructure/lib/user/user-construct.ts

chore: update user stack

---

source/lambda/online/common_logic/common_utils/pydantic_models.py
source/lambda/shared/langchain_integration/retrievers/databases/opensearch.py

Fixes #
<details>
This pull request includes modifications to two Python files:
1. `pydantic_models.py`: This file contains Pydantic models used for data validation and serialization/deserialization. The changes made in this file are likely related to updating or adding new models to support data structures used in the application.
2. `opensearch.py`: This file is part of the LangChain integration and contains code for interacting with an OpenSearch database. The modifications made to this file may involve improving the retrieval functionality, optimizing queries, or enhancing the overall integration with OpenSearch.
These changes aim to improve the codebase's functionality, performance, or maintainability. No …

feat: support public opensearch

---

source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/shared/langchain_integration/models/chat_models/sagemaker_models.py

feat: support sagemaker in online process

---

source/lambda/shared/langchain_integration/retrievers/databases/opensearch.py

fix: fix private opensearch issue

---

source/model/etl/code/main.py
source/model/etl/code/utils.py

- Add size constraints to prevent memory issues:
- Set maximum pixel limit (2000x3000) for scaled images
- Add minimum text line count threshold
- Limit maximum scale factor to 4.0x
- Improve PDF processing:
- Add 6M pixel limit for PDF pages
- Implement dynamic scaling based on page dimensions
- Enhance text detection scaling:
- Use 95th percentile for text height calculation
- Add checks for scaled image dimensions
- Optimize scale factor calculation
Fixes #
<details>
This pull request modifies the `main.py` and `utils.py` files in the `source/model/etl/code` directory. The changes aim to refactor the existing ETL (Extract, Transform, Load) process to improve performance and maintainability.
The key …

feat: optimize image scaling and add size limits for OCR processing

---

source/infrastructure/lib/model/model-construct.ts

Fixes #
<details>
This pull request modifies the `model-construct.ts` file in the `source/infrastructure/lib/model` directory. The changes aim to refactor the `ModelConstruct` class to improve code organization and maintainability. Specifically, the following updates have been made:
1. Extracted the logic for creating and managing DynamoDB tables into a separate `TableManager` class.
2. Refactored the `ModelConstruct` class to utilize the `TableManager` class for table-related operations.
3. Implemented error handling and logging mechanisms for better visibility into potential issues during table creation and management.
These changes do not introduce any breaking changes or new features. They primarily focus on …

fix: fix bge deploy

---

source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/shared/types.ts

feat: update vlm question for china region

---

source/infrastructure/lib/model/model-construct.ts

fix: fix bce embedding model path

---

source/lambda/shared/langchain_integration/models/rerank_models/__init__.py
source/lambda/shared/langchain_integration/models/rerank_models/sagemaker_rerank.py

fix: fix sagemaker rerank

---

source/lambda/job/dep/llm_bot_dep/figure_llm.py
source/lambda/shared/langchain_integration/models/chat_models/__init__.py
source/lambda/shared/langchain_integration/models/chat_models/openai_models.py
source/model/etl/code/figure_llm.py

Fixes #
<details>
This pull request introduces modifications to the figure_llm.py file in the source/lambda/job/dep/llm_bot_dep/ and source/model/etl/code/ directories, as well as changes to the __init__.py and openai_models.py files in the source/lambda/shared/langchain_integration/models/chat_models/ directory. The primary goal of these changes is to enhance the integration of the LangChain library with OpenAI models for improved language model functionality.
The modifications to figure_llm.py aim to optimize the performance and efficiency of the language model by streamlining the code and incorporating best practices. Additionally, the changes to the chat_models directory files are intended to provide better …

fix: fix various bugs

---

source/portal/src/pages/intention/IntentionDetail.tsx

Fixes #
<details>
This pull request modifies the `IntentionDetail.tsx` file in the `source/portal/src/pages/intention/` directory. The changes include refactoring the code to improve performance and maintainability. Specifically, the following updates have been made:
- Optimized the rendering of the intention detail page by implementing React.memo and useMemo hooks to prevent unnecessary re-renders.
- Refactored the data fetching logic to use the latest version of the API client, which improves error handling and provides better type safety.
- Replaced the use of deprecated lifecycle methods with functional components and hooks.
- Improved code readability by extracting reusable components and utility functions. …

fix: fix portal build error

---

source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/model/model-construct.ts

chore: set default reranker to bge reranker

---

source/lambda/online/common_logic/common_utils/response_utils.py
source/lambda/shared/langchain_integration/models/chat_models/sagemaker_models.py
source/lambda/shared/utils/websocket_utils.py

fix: fix api gw and online context window issue

---

source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/ui/ui-portal.ts

Fixes #
<details>
This pull request modifies the `magic-config.ts` and `ui-portal.ts` files to enhance the user interface (UI) experience for configuring and managing the application's infrastructure. The changes include:
- Updating the CLI configuration options to provide a more intuitive and user-friendly experience.
- Improving the UI portal's layout and styling to better align with the application's design guidelines.
- Refactoring the code to improve maintainability and extensibility.
These changes aim to streamline the infrastructure setup process and provide a more seamless experience for users interacting with the application's configuration and management tools.
File number involved in this PR: *2*, …

fix: fix front end deployment

---

source/infrastructure/lib/model/model-construct.ts

Fixes #
<details>
This pull request modifies the `model-construct.ts` file in the `source/infrastructure/lib/model` directory. The changes aim to refactor the existing code for better maintainability and performance optimization.
Specifically, the following improvements have been made:
1. Refactored the `ModelConstruct` class to separate concerns and improve code organization.
2. Optimized the `createModel` method by reducing unnecessary computations and improving algorithm efficiency.
3. Introduced caching mechanisms to avoid redundant calculations for frequently used data.
4. Updated error handling and logging mechanisms for better debugging and troubleshooting.
File number involved in this PR: *1*, unfold to …

fix: fix reranker deployment issue

---

source/infrastructure/cli/magic-config.ts

fix: update config

---

source/infrastructure/bin/config.ts
source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/api/intention-management.ts
source/infrastructure/lib/chat/chat-stack.ts
source/infrastructure/lib/knowledge-base/knowledge-base-stack.ts
source/infrastructure/lib/shared/types.ts
source/lambda/intention/intention.py
source/lambda/job/dep/llm_bot_dep/sm_utils.py
source/lambda/job/glue-job-script.py
source/lambda/shared/langchain_integration/retrievers/__utils/aos_retrievers.py
source/lambda/shared/langchain_integration/retrievers/databases/opensearch.py

feat: support custom aos secret

---

source/lambda/online/common_logic/common_utils/pydantic_models.py
source/lambda/online/common_logic/common_utils/warmup_utils.py
source/lambda/online/lambda_main/main.py
source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
source/lambda/online/requirements.txt
source/lambda/shared/langchain_integration/models/__init__.py
source/lambda/shared/langchain_integration/models/chat_models/bedrock_models.py
source/lambda/shared/langchain_integration/models/chat_models/brconnector_bedrock_models.py
source/lambda/shared/langchain_integration/models/chat_models/sagemaker_models.py
source/lambda/shared/langchain_integration/models/embedding_models/bedrock_embeddings.py
source/lambda/shared/langchain_integration/models/rerank_models/bedrock_rerank.py
source/lambda/shared/langchain_integration/models/rerank_models/sagemaker_rerank.py
source/lambda/shared/langchain_integration/retrievers/databases/__init__.py
source/lambda/shared/langchain_integration/retrievers/databases/opensearch.py
source/lambda/shared/langchain_integration/retrievers/opensearch_retrievers.py
source/lambda/shared/utils/boto3_utils.py
source/lambda/shared/utils/cache_utils.py

Fixes #
<details>
This pull request introduces several changes to the codebase, including bug fixes, new features, and improvements to existing functionality. The main highlights are:
1. **Pydantic Models Update**: The `pydantic_models.py` file has been modified to enhance the data validation and serialization capabilities of the application.
2. **Warmup Utils Addition**: A new file `warmup_utils.py` has been added to handle the warmup process for Lambda functions, ensuring efficient initialization and reducing cold start times.
3. **Lambda Main Modifications**: The `main.py` file, which serves as the entry point for Lambda functions, has been updated to incorporate the new warmup utilities and improve overall …

feat: online time optimize

---

source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/api/intention-management.ts
source/infrastructure/lib/shared/iam-helper.ts
source/lambda/etl/knowledge_base_search.py
source/lambda/shared/langchain_integration/retrievers/opensearch_retrievers.py
source/lambda/shared/utils/ddb_utils.py

feat: knowledge base search api

---

docs/api_doc/apis/api-prod-oas30.yaml
source/infrastructure/cli/magic-config.ts
source/infrastructure/lib/api/api-stack.ts
source/infrastructure/lib/api/chatbot-management.ts
source/infrastructure/lib/model/model-construct.ts
source/lambda/init_chatbot/main.py
source/lambda/shared/constant.py

Fixes #
<details>
This pull request includes modifications to the API documentation, CLI configuration, API stack, chatbot management, model construct, and Lambda functions related to initializing chatbots and shared constants. The changes are primarily focused on enhancing the chatbot functionality and improving the overall codebase.
File number involved in this PR: *7*, unfold to see the details:
<details>
| source/infrastructure/lib/api/api-stack.ts | 7 added, 1 removed | The code change adds the …

feat: support update endpoint in dynamodb with init_chatbot
