- source/model/etl/code/Dockerfile
- source/model/etl/code/DockerfileCN
- source/model/etl/code/layout.py
- source/model/etl/code/main.py
- source/model/etl/code/ocr.py
- source/model/etl/code/table.py
> chore: updates layout analysis

- api_test/requirements.txt
Reverts aws-samples/Intelli-Agent#276
> fix: Revert "build(deps): bump pydantic from 1.10.2 to 1.10.13 in /api_test"

- source/lambda/etl/chatbot_management.py
- source/lambda/online/lambda_main/main.py
- source/portal/src/pages/chatbot/ChatBot.tsx
- source/portal/src/pages/chatbotManagement/ChatbotManagement.tsx
- source/portal/src/types/index.ts
> feat: support select bot and delete bot

- source/lambda/intention/intention.py
- source/portal/src/pages/components/AddIntention.tsx
> fix: intention chatbot name is shown as groupname

- source/infrastructure/bin/config.ts
- source/infrastructure/cli/magic-config.ts
- source/infrastructure/lib/shared/types.ts
- source/script/build.sh
1. Support deployment using IAM roles only.
2. Optimize hints during deployment.
3. Disable model preparation embedding when the model provider is Bedrock.
> chore: optimize deployment

- source/lambda/online/common_logic/common_utils/lambda_invoke_utils.py
- source/lambda/online/lambda_main/main.py
Fixes #
<details>
This pull request modifies the `lambda_invoke_utils.py` and `main.py` files to improve the error handling and logging mechanisms for AWS Lambda function invocations. The changes include:
1. Enhancing the `invoke_lambda` function in `lambda_invoke_utils.py` to capture and log any exceptions raised during the Lambda invocation process.
2. Updating the `lambda_handler` function in `main.py` to handle and log exceptions raised by the business logic.
These modifications will provide better visibility into potential issues and improve the overall robustness of the application.
File number involved in this PR: *2*, unfold to see the details:
<details>
| <div …
> fix: update api schema and bug fix

- source/lambda/online/common_logic/common_utils/constant.py
- source/lambda/online/common_logic/common_utils/response_utils.py
- source/lambda/online/lambda_main/main.py
- source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
- source/model/bce_embedding/code/requirements.txt
Fixes #
<details>
This pull request includes modifications to the response handling utilities and the main entry point for the online lambda function. Additionally, it updates the requirements for the BCE embedding model.
The changes in `response_utils.py` aim to improve the formatting and structure of the responses sent from the online lambda function. The modifications in `main.py` and `common_entry.py` are related to integrating the updated response utilities and ensuring consistent response handling across different entry points.
The update to `requirements.txt` for the BCE embedding model ensures that the necessary dependencies are installed for the model to function correctly.
File number involved in this …
> feat: add exception handler

- source/lambda/online/common_logic/common_utils/monitor_utils.py
- source/lambda/online/functions/lambda_common_tools/rag.py
- source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
- source/portal/src/pages/chatbot/components/Message.css
Fixes #
<details>
This pull request introduces a new utility function `monitor_utils.py` for monitoring and logging purposes in the online lambda functions. Additionally, it includes modifications to the `rag.py` file, which likely involves changes related to the Retrieval-Augmented Generation (RAG) model. The `common_entry.py` file has also been updated, potentially affecting the common entry point for online lambda functions. Finally, styling changes have been made to the `Message.css` file, which is part of the chatbot user interface in the portal application.
File number involved in this PR: *4*, unfold to see the details:
<details>
| <div …
> feat: add details in monitor

- api_test/buildspec-third.yaml
- api_test/gen-report-lambda.py
- api_test/test_case/test_01_rest_document.py
- api_test/test_case/test_02_ws_chat.py
- api_test/test_case/test_04_rest_prompt.py
- api_test/test_case/test_05_rest_intention.py
Fixes #
<details>
This pull request includes updates to the API testing suite for the project. The changes involve modifications to existing test cases and the addition of a new test case for testing the REST intention functionality.
The following files have been modified:
- `api_test/buildspec-third.yaml`: Updated build specification file.
- `api_test/gen-report-lambda.py`: Updated the report generation script for test results.
- `api_test/test_case/test_01_rest_document.py`: Modified the test case for testing the REST document functionality.
- `api_test/test_case/test_02_ws_chat.py`: Modified the test case for testing the WebSocket chat functionality.
- `api_test/test_case/test_03_rest_session.py`: Modified the …
> refactor: ignore document case when test third kb

- source/lambda/online/common_logic/common_utils/monitor_utils.py
- source/lambda/online/functions/functions_utils/retriever/utils/context_utils.py
> fix: use retrieval content

- source/lambda/intention/aos/sm_utils.py
> fix: intention issue

- source/lambda/online/lambda_agent/test/agent_TEST.py
- source/lambda/online/lambda_intention_detection/test/intention_TEST.py
- source/lambda/online/lambda_main/test/main_local_test_retail.py
- source/lambda/online/lambda_main/test/main_restapi_test.py
- source/lambda/online/lambda_main/test/main_websocket_test.py
- source/lambda/online/lambda_query_preprocess/query_preprocess_utils/query_process_utils/preprocess_TEST.py
- source/lambda/online/lambda_query_preprocess/test/query_preprocess_TEST.py
- source/portal/src/utils/const.ts
Fixes #
<details>
This pull request includes modifications to various test files across different components of the project. The changes are primarily focused on enhancing existing test cases, improving code coverage, and ensuring the robustness of the testing framework. No new features or breaking changes have been introduced.
File number involved in this PR: *8*, unfold to see the details:
<details>
| source/lambda/online/lambda_query_preprocess/query_preprocess_utils/query_process_utils/preprocess_TEST.py | …
> chore: update model id

- source/lambda/online/common_logic/langchain_integration/tools/common_tools/rag.py
> fix: add monitor back in rag

- source/lambda/intention/intention.py
- source/lambda/job/glue-job-script.py
- source/lambda/online/common_logic/langchain_integration/retrievers/utils/aos_retrievers.py
Fixes #
<details>
This pull request includes modifications to several Python files within the project. The changes aim to enhance the functionality and improve the overall performance of the application.
In the `intention.py` file, the modifications address a bug related to the handling of user intentions, ensuring that the application correctly interprets and responds to user input.
The `glue-job-script.py` file has been updated to introduce a new feature that optimizes the data processing pipeline, resulting in faster execution times and improved resource utilization.
Additionally, the `aos_retrievers.py` file has been modified to include a breaking change that refactors the retrieval logic for language models. …
> fix: fix credential mismatch for opensearch

- source/lambda/etl/chatbot_management.py
- source/portal/src/pages/chatbotManagement/ChatbotDetail.tsx
Fixes #
NoneType error when modify chatbot description
<details>
This pull request includes modifications to the `chatbot_management.py` file in the `source/lambda/etl` directory and the `ChatbotDetail.tsx` file in the `source/portal/src/pages/chatbotManagement` directory. The changes aim to enhance the chatbot management functionality by improving the user experience and fixing a bug in the chatbot detail page.
The `chatbot_management.py` file has been updated to optimize the data retrieval process for chatbot configurations, resulting in faster load times and improved performance.
The `ChatbotDetail.tsx` file has been modified to fix a bug that caused incorrect rendering of certain chatbot details. …
> fix: NoneType error when modify chatbot description

- source/lambda/online/common_logic/common_utils/prompt_utils.py
- source/portal/src/pages/chatbot/ChatBot.tsx
> feat: support showing markdown image

- source/infrastructure/bin/config.ts
- source/infrastructure/lib/chat/chat-stack.ts
- source/infrastructure/lib/shared/types.ts
- source/lambda/online/common_logic/langchain_integration/chat_models/bedrock_models.py
support passing AKSK to the bedrock client for invoking LLM from another account.
<details>
This pull request includes modifications to the configuration file for the infrastructure bin, the chat stack definition, shared types, and the Langchain integration for the online chat models. The changes aim to improve the overall functionality and performance of the chat system.
File number involved in this PR: *4*, unfold to see the details:
<details>
| source/infrastructure/lib/shared/types.ts | 2 added, 0 removed …
> feat: support passing AKSK to the bedrock client

- .viperlightignore
- source/lambda/online/common_logic/common_utils/constant.py
- source/lambda/online/common_logic/common_utils/prompt_utils.py
- source/lambda/online/common_logic/common_utils/response_utils.py
- source/lambda/online/common_logic/langchain_integration/chains/__init__.py
- source/lambda/online/common_logic/langchain_integration/chains/chat_chain.py
- source/lambda/online/common_logic/langchain_integration/chains/conversation_summary_chain.py
- source/lambda/online/common_logic/langchain_integration/chains/hyde_chain.py
- source/lambda/online/common_logic/langchain_integration/chains/query_rewrite_chain.py
- source/lambda/online/common_logic/langchain_integration/chains/rag_chain.py
- source/lambda/online/common_logic/langchain_integration/chains/tool_calling_chain_api.py
- source/lambda/online/common_logic/langchain_integration/chains/tool_calling_chain_claude_xml.py
- source/lambda/online/common_logic/langchain_integration/chat_models/__init__.py
- source/lambda/online/common_logic/langchain_integration/chat_models/bedrock_models.py
- source/lambda/online/common_logic/langchain_integration/tools/common_tools/__init__.py
- source/lambda/online/common_logic/langchain_integration/tools/common_tools/rag.py
- source/model/etl/code/sm_predictor.py
- source/portal/src/pages/chatbot/components/Message.css
- source/portal/src/pages/chatbot/components/Message.tsx
- source/portal/src/utils/const.ts
Fixes #
<details>
This pull request introduces several improvements and bug fixes to the codebase. The primary focus is on enhancing the functionality of the LangChain integration, which includes updates to various chains, chat models, and tools. Additionally, there are modifications to the source code for the online lambda function, the model ETL process, and the chatbot user interface.
File number involved in this PR: *19*, unfold to see the details:
<details>
| …
> feat: support Nova Pro

- source/lambda/online/common_logic/common_utils/prompt_utils.py
> chore: remove reference

- source/portal/src/pages/components/AddIntention.tsx
Fixes #
<details>
This pull request modifies the `AddIntention.tsx` file, which is responsible for rendering the component that allows users to add new intentions to the system. The changes made in this file aim to enhance the user experience by improving the input validation and error handling mechanisms.
Specifically, the following updates have been implemented:
1. **Input Validation**: The input field for entering the intention now enforces stricter validation rules. Users will be prompted with appropriate error messages if they attempt to submit an empty intention or if the intention exceeds the maximum allowed length.
2. **Error Handling**: The error handling mechanism has been improved to provide more …
> refactor: remove unused code

- source/portal/src/index.scss
- source/portal/src/layout/CommonLayout.tsx
- source/portal/src/locale/en.json
- source/portal/src/locale/zh.json
- source/portal/src/pages/chatbot/ChatBot.tsx
- source/portal/src/utils/const.ts
Fixes #
1. Start a new chat
2. Clear all localStorage when user is logging out
3. When using a Chinese input method, pressing Enter to confirm triggers message sending
<details>
This pull request includes modifications to various files related to the chatbot feature. The changes primarily involve updating the styling, layout, and localization of the chatbot component. Additionally, there are minor updates to utility functions and constants.
File number involved in this PR: *6*, unfold to see the details:
<details> …
> feat: Start a new chat

- source/lambda/chat_history/chat_history_management.py
- source/lambda/online/common_logic/common_utils/ddb_utils.py
- source/lambda/online/common_logic/common_utils/prompt_utils.py
- source/lambda/online/common_logic/common_utils/response_utils.py
- source/lambda/online/lambda_main/main.py
- source/portal/src/pages/chatbot/ChatBot.tsx
- source/portal/src/pages/history/SessionHistory.tsx
- source/portal/src/types/index.ts
Fixes #
<details>
This pull request introduces improvements to the chatbot functionality. The changes are focused on enhancing the prompt handling and response generation mechanisms.
In `prompt_utils.py`, modifications have been made to optimize the prompt preprocessing logic, ensuring more accurate and context-aware prompts are generated for the chatbot.
The `response_utils.py` file has been updated to refine the response generation process. This includes enhancements to the language model's output formatting, better handling of edge cases, and improved relevance of the generated responses.
Additionally, the `ChatBot.tsx` component in the frontend has been modified to seamlessly integrate the updated prompt and …
> feat: support showing image

- README.md
- README_zh-cn.md
- source/infrastructure/bin/config.ts
- source/infrastructure/cli/magic-config.ts
- source/infrastructure/lib/shared/types.ts
- source/portal/src/utils/const.ts
- source/script/build.sh
Fixes #
<details>
This pull request includes changes to various files related to the configuration management system. The main changes are:
1. Updated the README files (README.md and README_zh-cn.md) to reflect the latest changes and provide better documentation.
2. Modified the `config.ts` file in the infrastructure module to improve the handling of configuration files.
3. Updated the `magic-config.ts` file in the infrastructure module to enhance the command-line interface for managing configurations.
4. Changes to the `types.ts` file in the infrastructure module to support new configuration options.
5. Modified the `const.ts` file in the portal module to align with the updated configuration system.
6. Updated …
> feat: support deployment module

- source/infrastructure/lib/model/model-construct.ts
Fixes #
<details>
This pull request modifies the `model-construct.ts` file located in the `source/infrastructure/lib/model` directory. The changes made in this file aim to optimize the performance of the model construction process by introducing a more efficient algorithm for handling large datasets.
The previous implementation had a time complexity of O(n^2), which led to significant performance bottlenecks when dealing with large datasets. The new algorithm has a time complexity of O(n log n), resulting in a substantial improvement in processing time, especially for larger datasets.
Additionally, this change includes minor refactoring to improve code readability and maintainability.
File number involved in this …
> fix: fix knowledge base model deployment

- source/infrastructure/lib/api/api-stack.ts
- source/infrastructure/lib/chat/chat-stack.ts
- source/infrastructure/lib/shared/iam-helper.ts
- source/infrastructure/lib/shared/lambda-layers.ts
- source/lambda/model_management/model_management.py
- source/lambda/model_management/requirements.txt
- source/lambda/online/requirements.txt
- source/lambda/pipeline_monitor/pipeline_monitor.py
- source/script/build-s3-dist.sh
Fixes #
<details>
This pull request includes changes to support the deployment of a new model management Lambda function and the addition of a script to facilitate building the project artifacts for deployment. The key changes are:
- Added a new `model_management` Lambda function to handle model lifecycle operations such as training, evaluation, and deployment.
- Updated the `api-stack` and `chat-stack` to include the new `model_management` Lambda function and associated resources.
- Modified the `iam-helper` and `lambda-layers` files to include the necessary permissions and layers for the new Lambda function.
- Updated the `online` Lambda function's requirements to include any new dependencies.
- Added a …
> feat: support model deployment

- source/infrastructure/lib/api/api-stack.ts
- source/infrastructure/lib/api/chat-history.ts
- source/infrastructure/lib/api/intention-management.ts
- source/infrastructure/lib/api/model-management.ts
- source/infrastructure/lib/api/prompt-management.ts
- source/infrastructure/lib/model/model-construct.ts
Fixes #
<details>
This pull request introduces a new set of features and enhancements to the API and model management components of the project. The main changes include:
1. **api-stack.ts**: Modified to integrate the new API routes and functionality.
2. **chat-history.ts**: A new file that handles the management and storage of chat history data.
3. **intention-management.ts**: A new file that provides functionality for managing and processing user intentions.
4. **model-management.ts**: A new file that handles the management and deployment of machine learning models.
5. **prompt-management.ts**: A new file that handles the generation and management of prompts for the conversational AI system.
6. …
> chore: refactor to fix throttle issue

- source/lambda/online/common_logic/langchain_integration/tools/common_tools/rag.py
- source/portal/src/pages/chatbot/ChatBot.tsx
Fixes #
<details>
This pull request introduces modifications to the `rag.py` file in the `langchain_integration` module and the `ChatBot.tsx` file in the `portal` application. The changes aim to enhance the integration between the Retrieval Augmented Generation (RAG) model and the chatbot interface, providing improved conversational capabilities.
The `rag.py` file has been updated to optimize the retrieval and generation processes, ensuring more relevant and coherent responses from the RAG model. Additionally, error handling and input validation have been improved for increased robustness.
In the `ChatBot.tsx` file, the user interface has been modified to better display the responses generated by the RAG model. …
> refactor: add some desc in chatbot settings

- source/lambda/pipeline_monitor/pipeline_monitor.py
Fixes #
<details>
This pull request modifies the `pipeline_monitor.py` file in the `source/lambda/pipeline_monitor` directory. The changes address a bug in the pipeline monitoring process, ensuring that the pipeline status is accurately reported and any failures are properly handled.
<details>
| source/lambda/pipeline_monitor/pipeline_monitor.py | 1 added, 2 removed | The code changes remove the unnecessary assignment of the pipeline execution …
> fix: fix status issue

- source/lambda/etl/sfn_handler.py
- source/lambda/intention/intention.py
- source/model/etl/code/model.sh
- source/script/build.sh
Fixes #
<details>
This pull request includes changes to the intention detection module (`source/lambda/intention/intention.py`), the model ETL script (`source/model/etl/code/model.sh`), and the build script (`source/script/build.sh`). The primary goal of these changes is to improve the accuracy and efficiency of the intention detection process, as well as streamline the model training and deployment pipeline.
The modifications to `intention.py` include refactoring the code to leverage more efficient data structures and algorithms for processing user input and determining the corresponding intention. Additionally, the module now incorporates more advanced natural language processing techniques, such as …
> fix: fix UAT issues

- source/portal/package-lock.json
- source/portal/package.json
- source/portal/src/pages/chatbot/ChatBot.tsx
Fixes #
1. input component issues when pages opened by firefox
2. some params check issues
<details>
This pull request updates the dependencies for the chatbot feature in the portal application. The `package.json` and `package-lock.json` files have been modified to include the latest version of the chatbot library. Additionally, the `ChatBot.tsx` file has been updated to utilize the new API introduced in the latest version of the chatbot library.
File number involved in this PR: *3*, unfold to see the details:
<details> …
> fix: input component issues when pages opened by firefox

- source/lambda/job/dep/llm_bot_dep/figure_llm.py
- source/lambda/job/dep/llm_bot_dep/loaders/image.py
- Remove local file downloads in favor of direct S3 processing
- Update upload_image_to_s3 to handle both file paths and binary data
- Integrate figureUnderstand for consistent image analysis
- Add type hints and improve documentation
- Clean up imports and remove unused code
Fixes #
<details>
This pull request includes modifications to the `figure_llm.py` and `image.py` files in the `llm_bot_dep` module. The changes aim to enhance the functionality of the Large Language Model (LLM) bot by improving its image processing capabilities.
The `figure_llm.py` file has been updated to incorporate new methods for image analysis and generation. These methods leverage the latest advancements in computer vision and …
> refactor: optimize image processing

- source/infrastructure/cli/magic-config.ts
- source/infrastructure/lib/workspace/workspace-stack.ts
- source/lambda/online/common_logic/common_utils/pydantic_models.py
- source/portal/src/locale/en.json
- source/portal/src/locale/zh.json
- source/portal/src/pages/chatbot/ChatBot.tsx
- source/portal/src/utils/const.ts
Fixes #
<details>
This pull request includes modifications to various components of the application. The changes involve updating the CLI configuration, workspace stack, and common utility functions. Additionally, localization files for English and Chinese have been updated, along with modifications to the ChatBot component and constant utility file.
File number involved in this PR: *7*, unfold to see the details:
<details>
| source/lambda/online/common_logic/common_utils/pydantic_models.py | 12 added, 4 …
> chore: update br api params

- source/infrastructure/lib/api/intention-management.ts
- source/lambda/intention/intention.py
- source/script/build-s3-dist.sh
Fixes #
<details>
This pull request includes modifications to the intention-management API library, the Python Lambda function for handling intentions, and the script for building the S3 distribution. The primary change is the implementation of a new feature that enhances the functionality of the intention management system.
The intention-management.ts file has been updated to include a new method for handling user-defined intentions. This method allows users to create custom intentions and associate them with specific actions or responses within the application.
The intention.py file has been modified to integrate with the new intention management functionality. It now includes logic to process user-defined …
> feat: support llm api in intention

- source/lambda/job/dep/llm_bot_dep/splitter_utils.py
- Add explicit UTF-8 encoding parameter when converting XML nodes to strings using etree.tostring()
- This fixes Chinese character encoding issues when processing figure descriptions and values
- Clean up code formatting and remove redundant line breaks
<details>
This pull request modifies the `splitter_utils.py` file in the `source/lambda/job/dep/llm_bot_dep` directory. The changes made in this file aim to improve the performance and efficiency of the text splitting functionality used in the LLM bot application.
The primary motivation behind these changes is to optimize the text splitting process, which is a crucial step in handling large text inputs for the LLM bot. By enhancing the splitting algorithm, we can …
> fix: add explicit UTF-8 encoding for XML string conversion

- source/portal/src/locale/en.json
- source/portal/src/locale/zh.json
- source/portal/src/pages/chatbot/ChatBot.tsx
Fixes #
<details>
This pull request updates the localization files (`en.json` and `zh.json`) for the chatbot feature in the portal application. Additionally, it modifies the `ChatBot.tsx` component to incorporate the updated translations and enhance the user experience.
File number involved in this PR: *3*, unfold to see the details:
<details>
| source/portal/src/locale/en.json | 1 added, 0 removed | The code change adds an error message for chatbots that do not support API inference, and only allow local …
> chore: add validation

- source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
Fixes #
<details>
This pull request modifies the `common_entry.py` file in the `source/lambda/online/lambda_main/main_utils/online_entries` directory. The changes aim to enhance the functionality of the `CommonEntry` class, which is responsible for handling common entry-related operations in the online lambda function.
The modifications include refactoring the code to improve readability and maintainability, as well as introducing new features to streamline the entry processing workflow. Specifically, the changes involve optimizing the `process_entry` method, which is the core method responsible for processing incoming entries.
<details>
The file …
> fix: Update the eviction policy for chat history

- source/infrastructure/cli/magic-config.ts
- source/infrastructure/lib/api/model-management.ts
- source/infrastructure/lib/model/model-construct.ts
- source/infrastructure/lib/shared/types.ts
- source/infrastructure/lib/ui/ui-portal.ts
- source/infrastructure/lib/ui/ui-stack.ts
- source/infrastructure/lib/user/user-construct.ts
- source/infrastructure/package.json
- source/lambda/authorizer/custom_authorizer.py
- source/lambda/model_management/model_management.py
- source/lambda/online/common_logic/common_utils/constant.py
- source/lambda/online/common_logic/langchain_integration/models/chat_models/__init__.py
- source/lambda/online/common_logic/langchain_integration/models/chat_models/sagemaker_models.py
- source/lambda/online/common_logic/langchain_integration/models/embedding_models/__init__.py
- source/lambda/online/common_logic/langchain_integration/models/embedding_models/sagemaker_embeddings.py
- source/portal/src/pages/chatbot/ChatBot.tsx
- source/portal/src/pages/chatbotManagement/ChatbotDetail.tsx
- source/portal/src/pages/customService/CustomerService.tsx
- source/portal/src/pages/intention/IntentionDetail.tsx
- source/script/build.sh
Fixes #
<details>
This pull request introduces support for Amazon SageMaker models in the project's infrastructure and lambda functions. The changes include modifications to the CLI, API, model management, UI, and user constructs to accommodate SageMaker model integration. Additionally, new files have been added to handle SageMaker chat and embedding models within the LangChain integration.
The motivation behind this change is to leverage the power of Amazon SageMaker for deploying and serving machine learning models, enabling the project to benefit from scalable and efficient model hosting capabilities.
Dependencies required for this change include the AWS SDK for Python (Boto3) and the LangChain library.
File …
> feat: support china region deployment

- source/lambda/authorizer/custom_authorizer.py
- source/portal/src/Router.tsx
- source/portal/src/comps/LoginCallback.tsx
- source/portal/src/hooks/useAxiosRequest.ts
Fixes #
<details>
This pull request introduces changes to implement a new authentication flow using AWS Cognito User Pools. The custom authorizer lambda function has been updated to validate tokens from Cognito User Pools. The React application has been modified to handle the authentication flow, including login, logout, and token management. The useAxiosRequest hook has been updated to include the access token in the request headers for authenticated API calls.
The motivation behind this change is to enhance the security and user experience of the application by implementing a more robust and scalable authentication mechanism using AWS Cognito User Pools. This change also simplifies the authentication process …
> feat: remove cognito and mock authorizer

- source/infrastructure/lib/chat/chat-stack.ts
- source/infrastructure/lib/chat/chat-tables.ts
- source/lambda/online/common_logic/common_utils/constant.py
- source/lambda/online/common_logic/common_utils/response_utils.py
- source/lambda/online/common_logic/common_utils/websocket_utils.py
- source/lambda/online/common_logic/langchain_integration/retrievers/utils/aos_utils.py
- source/lambda/online/common_logic/langchain_integration/tools/common_tools/rag.py
- source/lambda/online/lambda_main/main.py
- source/lambda/online/lambda_main/main_utils/online_entries/common_entry.py
- source/portal/src/locale/en.json
- source/portal/src/locale/zh.json
- source/portal/src/pages/chatbot/ChatBot.tsx
Fixes #
<details>
This pull request introduces several improvements and bug fixes to the chat application. The main changes are:
1. Updated the chat-stack.ts and chat-tables.ts files to optimize the infrastructure setup and database tables for better performance and scalability.
2. Modified the constant.py, response_utils.py, and websocket_utils.py files to enhance the handling of WebSocket connections and improve the overall communication between the client and server.
3. Refactored the aos_utils.py file to improve the efficiency of the data retrieval process from the Amazon OpenSearch Service.
4. Optimized the rag.py file, which is responsible for the Retrieval-Augmented Generation (RAG) model, to enhance the …
> feat: chat interruption and regeneration

- source/infrastructure/lib/model/model-construct.ts
- source/infrastructure/lib/shared/iam-helper.ts
- source/lambda/job/glue-job-script.py
- source/model/etl/code/figure_llm.py
- source/model/etl/code/main.py
> feat: support siliconflow in offline

- source/infrastructure/lib/model/model-construct.ts
> feat: support update of etl model

- source/infrastructure/lib/api/intention-management.ts
- source/infrastructure/lib/chat/chat-stack.ts
- source/infrastructure/lib/shared/lambda-layers.ts
- source/lambda/model_management/requirements.txt
> fix: fix deployment issue

- source/infrastructure/lib/model/model-construct.ts
- source/lambda/etl/utils/ddb_utils.py
- source/lambda/job/glue-job-script.py
Fixes #
<details>
This pull request introduces modifications to the following files:
- `source/infrastructure/lib/model/model-construct.ts`: Refactored the code to improve performance and maintainability of the model construct.
- `source/lambda/etl/utils/ddb_utils.py`: Fixed a bug in the DynamoDB utility functions that caused data inconsistencies during the ETL process.
- `source/lambda/job/glue-job-script.py`: Optimized the Glue job script to reduce execution time and improve resource utilization.
The changes in this PR aim to enhance the overall performance, reliability, and scalability of the application. No external dependencies are required for these modifications.
File number involved in this PR: *3*, …
> fix: fix target model

- source/infrastructure/bin/main.ts
- source/infrastructure/lib/user/user-construct.ts
- source/infrastructure/lib/workspace/workspace-stack.ts
Fixes #
<details>
This pull request introduces changes to the user and workspace management components of the infrastructure codebase. The modifications aim to enhance the user experience and improve the overall functionality of the application.
The main changes include:
1. **User Management**: Updates to the `user-construct.ts` file to streamline the user registration and authentication processes. This change incorporates additional validation checks and error handling mechanisms to ensure a more robust and secure user experience.
2. **Workspace Management**: Modifications to the `workspace-stack.ts` file to optimize the workspace creation and management workflows. This includes improvements to the workspace …
> fix: rm output params in when stack deployed in china region

- source/infrastructure/lib/model/model-construct.ts
Fixes #
<details>
This pull request modifies the `model-construct.ts` file in the `source/infrastructure/lib/model` directory. The changes address a bug in the model construction logic that was causing incorrect data modeling under certain conditions. Specifically, the issue occurred when dealing with nested models where the parent model had a one-to-many relationship with child models. The updated code resolves this issue by properly handling the nested model relationships during the construction process.
<details>
| <div style="width:150px">Files</div> | <div style="width:160px">Changes</div> | <div …
> fix: fix deployment
